name: myapp
description: "El Mundo de Alegría - Premium Coloring Book"
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  floodfill_image: ^0.0.8
  confetti: ^0.7.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  file_picker: ^8.0.3
  share_plus: ^9.0.0  # 🚀 NUEVO PAQUETE PARA GUARDAR/COMPARTIR FOTOS
  audioplayers: ^5.2.1 # 🚀 PAQUETE PARA AUDIO AMBIENTAL Y EFECTOS
  in_app_purchase: ^3.1.13 # 🚀 PAQUETE PARA PAGOS REALES

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0 # 🚀 VERSIÓN CORREGIDA (Downgrade)

# 🚀 CONFIGURACIÓN DEL ÍCONO DE LA APP
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
    - assets/canva/
    - assets/Dino/
    - assets/Abecedario_MundoAlegria/
    - assets/logo.png