import 'idiomas.dart';

/// Copy for the parent-only flows. Never promise photo-to-outline conversion.
String textoAdulto(String key) {
  final locale = Traductor.idiomaActual;
  return _textos[locale]?[key] ?? _textos['en']![key] ?? key;
}

const _textos = <String, Map<String, String>>{
  'es': {
    'adults': 'Para adultos',
    'gate': 'Escribe el resultado para continuar',
    'continue': 'Continuar',
    'cancel': 'Cancelar',
    'discard': '¿Descartar los cambios de esta página?',
    'discardDetail':
        'Comparte una copia antes de salir si quieres conservarla.',
    'yesDiscard': 'Descartar',
    'share': 'Compartir una copia',
    'shareError': 'No se pudo compartir. Tu dibujo sigue aquí.',
    'importError': 'No se pudo importar. Inténtalo de nuevo.',
    'importDone': 'Importadas',
    'skipped': 'Omitidas',
    'infinite': 'Libro Infinito',
    'coming': 'Compra aún no disponible',
    'offer': 'Importación ilimitada de láminas PNG y JPG mediante una compra única. Sin anuncios ni suscripción. Las fotos se abren tal como son; no se convierten en contornos.',
    'trial': 'Puedes probar una lámina propia gratis. No hay ningún cobro en esta versión.',
    'import': 'Añadir lámina',
    'clear': 'Limpiar página',
    'close': 'Volver al libro',
    'undo': 'Deshacer trazo o sello',
    'previous': 'Página anterior',
    'next': 'Página siguiente',
    'audio': 'Sonido',
    'deleteError': 'No se pudo borrar el pack. Inténtalo de nuevo.',
  },
  'en': {
    'adults': 'For adults',
    'gate': 'Enter the answer to continue',
    'continue': 'Continue',
    'cancel': 'Cancel',
    'discard': 'Discard changes on this page?',
    'discardDetail': 'Share a copy before leaving if you want to keep it.',
    'yesDiscard': 'Discard',
    'share': 'Share a copy',
    'shareError': 'Could not share. Your drawing is still here.',
    'importError': 'Could not import. Please try again.',
    'importDone': 'Imported',
    'skipped': 'Skipped',
    'infinite': 'Infinite Book',
    'coming': 'Purchase not available yet',
    'offer': 'Unlimited PNG and JPG coloring-sheet imports with a one-time purchase. No ads or subscription. Photos open as they are; they are not converted to outlines.',
    'trial':
        'Try one personal sheet for free. This version does not charge you.',
    'import': 'Add a sheet',
    'clear': 'Clear page',
    'close': 'Back to book',
    'undo': 'Undo stroke or sticker',
    'previous': 'Previous page',
    'next': 'Next page',
    'audio': 'Sound',
    'deleteError': 'Could not delete the pack. Please try again.',
  },
  'pt': {
    'adults': 'Para adultos',
    'gate': 'Digite o resultado para continuar',
    'continue': 'Continuar',
    'cancel': 'Cancelar',
    'discard': 'Descartar as alterações desta página?',
    'discardDetail':
        'Compartilhe uma cópia antes de sair para guardar o desenho.',
    'yesDiscard': 'Descartar',
    'share': 'Compartilhar uma cópia',
    'shareError': 'Não foi possível compartilhar. Seu desenho continua aqui.',
    'importError': 'Não foi possível importar. Tente novamente.',
    'importDone': 'Importadas',
    'skipped': 'Ignoradas',
    'infinite': 'Livro Infinito',
    'coming': 'Compra ainda indisponível',
    'offer': 'Importações ilimitadas de desenhos PNG e JPG com pagamento único. Sem anúncios nem assinatura. Fotos abrem como são; não são convertidas em contornos.',
    'trial': 'Experimente um desenho próprio gratuitamente. Esta versão não cobra nada.',
    'import': 'Adicionar desenho',
    'clear': 'Limpar página',
    'close': 'Voltar ao livro',
    'undo': 'Desfazer traço ou adesivo',
    'previous': 'Página anterior',
    'next': 'Próxima página',
    'audio': 'Som',
    'deleteError': 'Não foi possível apagar o pacote. Tente novamente.',
  },
  'de': {
    'adults': 'Für Erwachsene',
    'gate': 'Zum Fortfahren das Ergebnis eingeben',
    'continue': 'Weiter',
    'cancel': 'Abbrechen',
    'discard': 'Änderungen auf dieser Seite verwerfen?',
    'discardDetail':
        'Teile vorher eine Kopie, wenn du das Bild behalten möchtest.',
    'yesDiscard': 'Verwerfen',
    'share': 'Eine Kopie teilen',
    'shareError': 'Teilen fehlgeschlagen. Dein Bild ist noch da.',
    'importError': 'Import fehlgeschlagen. Bitte erneut versuchen.',
    'importDone': 'Importiert',
    'skipped': 'Übersprungen',
    'infinite': 'Unendliches Malbuch',
    'coming': 'Kauf noch nicht verfügbar',
    'offer': 'Unbegrenzt PNG- und JPG-Malvorlagen mit einem einmaligen Kauf importieren. Keine Werbung, kein Abo. Fotos werden unverändert geöffnet, nicht in Konturen umgewandelt.',
    'trial': 'Probiere eine eigene Vorlage kostenlos aus. Diese Version berechnet nichts.',
    'import': 'Vorlage hinzufügen',
    'clear': 'Seite leeren',
    'close': 'Zurück zum Buch',
    'undo': 'Strich oder Sticker rückgängig',
    'previous': 'Vorherige Seite',
    'next': 'Nächste Seite',
    'audio': 'Ton',
    'deleteError': 'Löschen fehlgeschlagen. Bitte erneut versuchen.',
  },
  'fr': {
    'adults': 'Pour les adultes',
    'gate': 'Saisissez le résultat pour continuer',
    'continue': 'Continuer',
    'cancel': 'Annuler',
    'discard': 'Abandonner les modifications de cette page ?',
    'discardDetail':
        'Partagez une copie avant de quitter pour garder le dessin.',
    'yesDiscard': 'Abandonner',
    'share': 'Partager une copie',
    'shareError': 'Partage impossible. Votre dessin est toujours ici.',
    'importError': 'Importation impossible. Réessayez.',
    'importDone': 'Importées',
    'skipped': 'Ignorées',
    'infinite': 'Livre Infini',
    'coming': 'Achat pas encore disponible',
    'offer': 'Importations illimitées de coloriages PNG et JPG avec un achat unique. Sans publicité ni abonnement. Les photos restent telles quelles, sans conversion en contours.',
    'trial': 'Essayez gratuitement une image personnelle. Cette version ne facture rien.',
    'import': 'Ajouter une image',
    'clear': 'Effacer la page',
    'close': 'Retour au livre',
    'undo': 'Annuler trait ou autocollant',
    'previous': 'Page précédente',
    'next': 'Page suivante',
    'audio': 'Son',
    'deleteError': 'Suppression impossible. Réessayez.',
  },
};
